---
- hosts: routers
  gather_facts: no
  tasks:
  - name: Lets configure login banner
    ios_banner:
      banner: login
      text: |
                                                        ,
                                                ,d'
                                                ,d   ,d88888.
                                                Y888P'    `8
                                                            8   d8P
                                                          :'  dP dP
          ,88B    ,88B             ,d8B                           dP
          ,88 P   ,88 P       88P ,d8  P   ,od8888888888888bo.     d8P    ,od88b.     ,d88b.
        ,88     ,88         ,88  88     ,'      ,dP'             dP dP       `88b  ,d8  `8b
        88      88        ,d888  88           ,dP'              dP   dP       888,d8'    88
        `88     `88     ,d8P 88  88      .   ,dP'              dP     dP      888'       88
          `88    d888  ,d8P   88  `q8   d8'  ,dP'      .    ,d dP       dP b.  888        88
          `Y8888P  Y8888P'  ,88    `Y888    88         'b  `Y8P         d8P   888        88
                            88'             88         ,8'
                            88              `Yb.     ,dP'
                            ,88                `Y88888P'
                          ,8P'
                          d8
                          88
                        8P
                        8'
                      8
                      "
                    ############################################################
                    "The Doors of Durin, Lord of Moria. Speak, friend, and enter.
                    I, Narvi, made them. Celebrimbor of Hollin drew these signs."
        #############################################################
      state: present

  - name: Lets configure motd banner
    ios_banner:
      banner: motd
      text: |
        ############################################################
        "One Router to rule them all, 
        One Router to find them, 
        One Router to bring them all and in the darkness bind them"
        ############################################################
      state: present

  - name: Show the version of the devices
    ios_command:
      commands:
        - show version
    register: version

  - name: Show the value of version
    debug:
      msg: "{{version}}"

  - name: Show the ip interfaces
    ios_command:
      commands:
        - show ip int brief
    register: ipint
  - name: Show the value of ipint
    debug:
      msg: "{{ipint}}"