---
- hosts: routers
  gather_facts: no
  tasks:
  - name: Configuración banner login
    ios_banner:
      banner: login
      text: |
        ############################################################
        "The Doors of Durin, Lord of Moria. Speak, friend, and enter"
        #############################################################
      state: present

  - name: Configuración banner motd
    ios_banner:
      banner: motd
      text: |
        ###########################################################
        "One Router to rule them all, 
        One Router to find them, 
        One Router to bring them all and in the darkness bind them"
        ###########################################################
      state: present