---
## Playbook to get system time and append it to backup files
- hosts: Rick1

  tasks:
  - name: Show IP int brief 
    ios_command:
      commands: show ip int brief  
    register: config

  - name: Save output to ~/network-programmability/backups/
    copy:
      content: "{{config.stdout[0]}}"
      dest: ~/proyecto/ip/ips.txt

- hosts: Rick2

  tasks:
  - name: Show IP int brief 
    ios_command:
      commands: show ip int brief  
    register: config

  - name: Insert a line at the end 
    lineinfile:
      path: ~/proyecto/ip/ips.txt
      line: "{{config.stdout[0]}}"

- hosts: Rick3

  tasks:
  - name: Show IP int brief 
    ios_command:
      commands: show ip int brief  
    register: config

  - name: Insert a line at the end 
    lineinfile:
      path: ~/proyecto/ip/ips.txt
      line: "{{config.stdout[0]}}"