---
## Playbook to get system time and append it to backup files
- hosts: Rick1

  tasks:
  - name: Show IP int brief 
    ios_command:
      commands: show ip int brief  
    register: config

  - name: Save output to ~/network-programmability/backups/
    copy:
      content: "{{config.stdout[0]}}"
      dest: "~/network-programmability/backups/ship.txt"

- hosts: Rick2

  tasks:
  - name: Show IP int brief 
    ios_command:
      commands: show ip int brief  
    register: config

  - name: Save output to ~/network-programmability/backups/
    lineinfile:
      path: ~/network-programmability/backups/ship.txt"
      line: "{{config.stdout[0]}}"